### ISSUE TITLE
npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/zeppelin-tabledata

### ISSUE THREAD

**Issue by zhu7ge** [AhyoungRyu/zeppelin-highcharts-spline#1]
Hi, ahyoung 
 Thank you for giving so cool features,but when I do following your steps,I get the error,
The error information as follows
`npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/zeppelin-tabledata`,
I'm new hand for using zeppelin,I don't know where is the zeppelin-tabledata,please for help,
Thank you very much!

**Comment by AhyoungRyu** [comment]
@zhu7ge Glad to hear that you tried! Actually you don't need to install this by yourself like other npm pkgs.  This pkg is just for Zeppelin. So you don't need like 
```
npm install ...
```
in your machine.

Just start Zeppelin -> Go to Helium menu as https://github.com/AhyoungRyu/zeppelin-highcharts-spline#how-to-use describes. Which version of Zeppelin are you using now?

 - If you're using `0.7.0`,
 Copy [this file] under `YOUR_ZEPPELIN_HOME/helium/`(if you don't have, create new one) -> restart Zeppelin -> Go to Helium menu -> click enable btn `zeppelin-highcharts-spline` package

 - If you're using `0.8.0-SNAPSHOT` 
Just start Zeppelin -> Go to Helium menu -> click enable btn `zeppelin-highcharts-spline` package 

Hope this helps!

**Comment by zhu7ge** [comment]
@AhyoungRyu Thank you for your reply,
I'm using Zeppelin 0.7.0, I follow your steps as https://github.com/AhyoungRyu/zeppelin-highcharts-spline#how-to-use describes, and My OS is centos7.

Here are my files
`[hadoop@slave4 helium]$ ll
-rw-rw-r-- 1 hadoop hadoop 1021 Feb 17 14:53 zeppelin-highcharts-spline.json`

I done your steps, in zeppelin web can see the icon, but when I click the icon,  
the following is blank, I think that  maybe installation failed.
I'll try again, Thank you for your reply!

**Comment by AhyoungRyu** [comment]
@zhu7ge You mean in the graph? You need to fill the setting blanks like below.
![record](https://cloud.githubusercontent.com/assets/10060731/23059182/987ec71c-f53b-11e6-9a6c-1344eb6d0679.gif)

**Comment by zhu7ge** [comment]
@AhyoungRyu  I'm sorry,I no click settings btn, so it's blank,
When I click ,and fill the settings, It's running OK.

I am too careless, Thank you very much for your answer,
I'm not good at English, it's the first time to communicate with foreigners. 
Thanks again!

**Comment by AhyoungRyu** [comment]
@zhu7ge No worries. Thanks for your interest and hope all was good!
